
# History 

There are three basic and interwoven principles of toxicology: 

1) dose-response 
2) `hazard x exposure = risk`
3) individual sensitivity. 

While these principles may form much of the foundation of toxicology, 
when it comes to any specific substance there is
likely to be controversy. 
Disagreement may arise on the relative importance of any one of
these principles while trying to evaluate implications for public health. 
Exploring these principles is an essential first step before examining their application to any specific substance. 


## Early Days

Our ancient ancestors worried about being poisoned ether accidentally or on purpose. The formal study of poisons (and thus toxicology) began 500 years ago during the
Renaissance, a period of incredible change and challenge to traditional thought.

- Phillippus Aureolus was born in Switzerland a year after Columbus 
  sailed in 1493. He took the pseudonym of Theophrastus Bombastus von Hohenheim 
  and still later invented the name Paracelsus (1493-1541). 
  
  This name may signify his desire to move
  beyond the Roman philosopher and medical writer Aulus Cornelius Celsus (CcAD3-64),
  who promoted cleanliness and recommend the washing of wounds with an antiseptic such
  as vinegar. Paracelsus’s claim to toxicology is that he elegantly 
  stated the principle of dose-response as 
  “_All substances are poisons; there is none, which is
  not a poison. The right dose differentiates a poison from a remedy._” 
 
 











